"""L5 Issue Generator — create GitHub issues for verified practices."""

from __future__ import annotations

import logging

import httpx

from src.models.practice import Practice, VerdictStatus, VerificationResult
from src.config import GitHubConfig

logger = logging.getLogger(__name__)


class IssueGenerator:
    """Create GitHub issues on the target spec repository."""

    def __init__(self, github_config: GitHubConfig):
        self.config = github_config
        self.session = httpx.Client(
            base_url="https://api.github.com",
            headers={
                "Authorization": f"Bearer {github_config.token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=30.0,
        )

    def create_issue(self, practice: Practice, verification: VerificationResult) -> dict | None:
        """Create a GitHub issue for a verified practice."""
        title = f"[AI-Coding-Spec] Suggestion: {practice.summary[:80]}"
        body = self._build_issue_body(practice, verification)

        repo = self.config.target_repo
        try:
            resp = self.session.post(
                f"/repos/{repo}/issues",
                json={"title": title, "body": body, "labels": ["spec-evolution", "automated"]},
            )
            if resp.status_code == 201:
                issue = resp.json()
                logger.info("Created issue #%d: %s", issue["number"], issue["html_url"])
                return issue
            else:
                logger.error("Failed to create issue: %d %s", resp.status_code, resp.text)
                return None
        except Exception as e:
            logger.error("Error creating issue: %s", e)
            return None

    @staticmethod
    def _build_issue_body(practice: Practice, verification: VerificationResult) -> str:
        """Build the issue body with full evidence chain."""
        status_emoji = {
            VerdictStatus.VERIFIED: "✅",
            VerdictStatus.FAILED: "❌",
            VerdictStatus.NEEDS_REVIEW: "⚠️",
            VerdictStatus.REJECTED: "🚫",
        }

        logic_emoji = status_emoji.get(verification.logic_verdict, "❓")
        project_emoji = status_emoji.get(verification.project_verdict, "❓") if verification.project_verdict else "➖"
        final_emoji = status_emoji.get(verification.final_verdict, "❓") if verification.final_verdict else "❓"

        return f"""## Source
- **Twitter**: [{practice.source.author_handle}](https://x.com/{practice.source.author_handle})
- **Original**: https://x.com/{practice.source.author_handle}/status/{practice.source.id}
- **Engagement**: {practice.source.metrics.get('likes', 0)} likes, {practice.source.metrics.get('retweets', 0)} retweets

## Practice Description
{practice.detail}

## Tags
`{"`, `".join(practice.tags)}`

## Verification Results

| Check | Result |
|-------|--------|
| Logic Verification | {logic_emoji} {verification.logic_verdict} |
| Project Verification | {project_emoji} {verification.project_verdict or 'N/A'} |
| **Final Verdict** | **{final_emoji} {verification.final_verdict or 'pending'}** |

### Logic Reasoning
{verification.logic_reasoning or 'No logic reasoning available'}

### Project Evidence
```
{verification.project_evidence or 'No project verification performed'}
```

## Suggested Spec Change

{practice.suggested_spec_doc or 'TBD'} → {practice.suggested_section or 'new section'}

## Confidence
- LLM classification confidence: **{practice.confidence:.0%}**
- Source trust score: (see account manager)

---

*This issue was automatically generated by [ai-spec-evolution](https://github.com/your-org/ai-spec-evolution).*
*Please review and accept/reject as appropriate.*
"""
